    create table department (
        id bigint generated by default as identity,
        description varchar(2000) not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table department_notice (
        author_id bigint not null,
        created_at timestamp(6) not null,
        department_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint not null,
        content varchar(10000) not null,
        title varchar(255) not null,
        primary key (id)
    );

    create table document (
        author_id bigint not null,
        created_at timestamp(6) not null,
        department_id bigint not null,
        id bigint generated by default as identity,
        required_position enum ('ADMIN','ASSISTANT_MANAGER','DEPUTY_GENERAL_MANAGER','EXECUTIVE','GENERAL_MANAGER','MANAGER','STAFF') default 'STAFF' not null,
        primary key (id)
    );

    create table document_activity (
        version_number integer not null,
        actor_id bigint not null,
        document_id bigint not null,
        id bigint generated by default as identity,
        occurred_at timestamp(6) not null,
        version_id bigint not null,
        actor_nickname varchar(100) not null,
        document_title varchar(255) not null,
        action enum ('APPROVED','CREATED','READ','REJECTED','REVIEW_OPENED') not null,
        actor_position enum ('ADMIN','ASSISTANT_MANAGER','DEPUTY_GENERAL_MANAGER','EXECUTIVE','GENERAL_MANAGER','MANAGER','STAFF') not null,
        primary key (id)
    );

    create table document_version (
        version_number integer not null,
        created_at timestamp(6) not null,
        document_id bigint not null,
        id bigint generated by default as identity,
        reviewed_at timestamp(6),
        reviewed_by_id bigint,
        title varchar(255) not null,
        content clob not null,
        status enum ('APPROVED','ARCHIVED','DRAFT','PENDING_REVIEW','PENDING_SECURITY_APPROVAL','REJECTED') not null,
        primary key (id),
        constraint UK_document_version_number unique (document_id, version_number)
    );

    create table users (
        created_at timestamp(6) not null,
        department bigint,
        id bigint generated by default as identity,
        nickname varchar(100) not null unique,
        email varchar(255) not null unique,
        password varchar(255) not null,
        account_status enum ('ACTIVE','BAN','DELETED','LOCKED') not null,
        position enum ('ADMIN','ASSISTANT_MANAGER','DEPUTY_GENERAL_MANAGER','EXECUTIVE','GENERAL_MANAGER','MANAGER','STAFF') not null,
        primary key (id)
    );