-- Upgrade the existing local schema without deleting business data.
-- New databases skip these ALTER statements and use the complete definitions below.
ALTER TABLE IF EXISTS department ADD COLUMN IF NOT EXISTS closed boolean default false not null;
ALTER TABLE IF EXISTS department ADD COLUMN IF NOT EXISTS revision bigint default 0 not null;
ALTER TABLE IF EXISTS department_notice ADD COLUMN IF NOT EXISTS scope enum ('DEPARTMENT','GLOBAL') default 'DEPARTMENT' not null;
ALTER TABLE IF EXISTS document ADD COLUMN IF NOT EXISTS archived boolean default false not null;
ALTER TABLE IF EXISTS document ADD COLUMN IF NOT EXISTS project_id bigint;
ALTER TABLE IF EXISTS document ADD COLUMN IF NOT EXISTS revision bigint default 0 not null;
ALTER TABLE IF EXISTS document ADD COLUMN IF NOT EXISTS category enum ('DESIGN','OTHER','SECURITY_REVIEW','TEST_REPORT') default 'OTHER' not null;
ALTER TABLE IF EXISTS document ADD COLUMN IF NOT EXISTS classification enum ('CONFIDENTIAL','INTERNAL','RESTRICTED') default 'INTERNAL' not null;
ALTER TABLE IF EXISTS document ADD COLUMN IF NOT EXISTS required_position enum ('ADMIN','ASSISTANT_MANAGER','DEPUTY_GENERAL_MANAGER','EXECUTIVE','GENERAL_MANAGER','MANAGER','STAFF') default 'STAFF' not null;
ALTER TABLE IF EXISTS document_version ADD COLUMN IF NOT EXISTS editor_id bigint;
ALTER TABLE IF EXISTS document_version ADD COLUMN IF NOT EXISTS revision bigint default 0 not null;
ALTER TABLE IF EXISTS document_version ADD COLUMN IF NOT EXISTS security_reviewed_at timestamp(6);
ALTER TABLE IF EXISTS document_version ADD COLUMN IF NOT EXISTS security_reviewer_id bigint;
ALTER TABLE IF EXISTS document_version ADD COLUMN IF NOT EXISTS editor_name varchar(100);
ALTER TABLE IF EXISTS document_version ADD COLUMN IF NOT EXISTS security_reviewer_name varchar(100);
ALTER TABLE IF EXISTS document_version ADD COLUMN IF NOT EXISTS archived_from enum ('APPROVED','ARCHIVED','DRAFT','PENDING_REVIEW','PENDING_SECURITY_APPROVAL','REJECTED');
ALTER TABLE IF EXISTS document_version ADD COLUMN IF NOT EXISTS reviewed_at timestamp(6);
ALTER TABLE IF EXISTS document_version ADD COLUMN IF NOT EXISTS reviewed_by_id bigint;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS credentials_version bigint default 0 not null;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS revision bigint default 0 not null;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS clearance enum ('CONFIDENTIAL','INTERNAL','RESTRICTED') default 'INTERNAL' not null;
ALTER TABLE IF EXISTS department_notice ALTER COLUMN department_id DROP NOT NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN account_status ENUM('ACTIVE','BAN','DELETED','LOCKED') NOT NULL;

    create table if not exists attachment (
        id bigint generated by default as identity,
        size bigint not null,
        uploaded_at timestamp(6) with time zone,
        uploaded_by bigint,
        version_id bigint not null,
        storage_key varchar(40) not null,
        sha256 varchar(64) not null,
        content_type varchar(100) not null,
        filename varchar(255) not null,
        primary key (id)
    );

    create table if not exists audit_head (
        id bigint not null,
        sequence bigint not null,
        record_hash varchar(64) not null,
        primary key (id)
    );

    create table if not exists audit_record (
        id bigint not null,
        occurred_at timestamp(6) with time zone not null,
        project_id bigint,
        target_id bigint,
        target_type varchar(40) not null,
        previous_hash varchar(64) not null,
        record_hash varchar(64) not null,
        action varchar(80) not null,
        actor varchar(100) not null,
        description varchar(4000) not null,
        primary key (id)
    );

    create table if not exists department (
        closed boolean default false not null,
        id bigint generated by default as identity,
        revision bigint default 0 not null,
        description varchar(2000) not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table if not exists department_notice (
        author_id bigint not null,
        created_at timestamp(6) not null,
        department_id bigint,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint not null,
        content varchar(10000) not null,
        title varchar(255) not null,
        scope enum ('DEPARTMENT','GLOBAL') default 'DEPARTMENT' not null,
        primary key (id)
    );

    create table if not exists document (
        archived boolean default false not null,
        author_id bigint not null,
        created_at timestamp(6) not null,
        department_id bigint not null,
        id bigint generated by default as identity,
        project_id bigint,
        revision bigint default 0 not null,
        category enum ('DESIGN','OTHER','SECURITY_REVIEW','TEST_REPORT') default 'OTHER' not null,
        classification enum ('CONFIDENTIAL','INTERNAL','RESTRICTED') default 'INTERNAL' not null,
        required_position enum ('ADMIN','ASSISTANT_MANAGER','DEPUTY_GENERAL_MANAGER','EXECUTIVE','GENERAL_MANAGER','MANAGER','STAFF') default 'STAFF' not null,
        primary key (id)
    );

    create table if not exists document_activity (
        version_number integer not null,
        actor_id bigint not null,
        document_id bigint not null,
        id bigint generated by default as identity,
        occurred_at timestamp(6) not null,
        version_id bigint not null,
        actor_nickname varchar(100) not null,
        document_title varchar(255) not null,
        action enum ('APPROVED','CREATED','READ','REJECTED','REVIEW_OPENED') not null,
        actor_position enum ('ADMIN','ASSISTANT_MANAGER','DEPUTY_GENERAL_MANAGER','EXECUTIVE','GENERAL_MANAGER','MANAGER','STAFF') not null,
        primary key (id)
    );

    create table if not exists document_version (
        version_number integer not null,
        created_at timestamp(6) not null,
        document_id bigint not null,
        editor_id bigint,
        id bigint generated by default as identity,
        reviewed_at timestamp(6),
        reviewed_by_id bigint,
        revision bigint default 0 not null,
        security_reviewed_at timestamp(6),
        security_reviewer_id bigint,
        editor_name varchar(100),
        security_reviewer_name varchar(100),
        title varchar(255) not null,
        archived_from enum ('APPROVED','ARCHIVED','DRAFT','PENDING_REVIEW','PENDING_SECURITY_APPROVAL','REJECTED'),
        content clob not null,
        status enum ('APPROVED','ARCHIVED','DRAFT','PENDING_REVIEW','PENDING_SECURITY_APPROVAL','REJECTED') not null,
        primary key (id),
        constraint UK_document_version_number unique (document_id, version_number)
    );

    create table if not exists engineering_change (
        assignee_id bigint,
        base_version_id bigint,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        project_id bigint not null,
        requester_id bigint,
        resolved_at timestamp(6) with time zone,
        resolved_version_id bigint,
        revision bigint not null,
        title varchar(200) not null,
        assignee_name varchar(255),
        requester_name varchar(255),
        description clob not null,
        resolution clob,
        status enum ('IN_PROGRESS','OPEN','REJECTED','RESOLVED') not null,
        primary key (id)
    );

    create table if not exists nonconformity (
        closed boolean not null,
        closed_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone,
        failed_run_id bigint,
        id bigint generated by default as identity,
        passing_run_id bigint,
        project_id bigint not null,
        revision bigint not null,
        closed_by varchar(255),
        corrective_action clob,
        description clob,
        primary key (id)
    );

    create table if not exists notification (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        read_at timestamp(6) with time zone,
        recipient_id bigint not null,
        kind varchar(80) not null,
        link varchar(300) not null,
        message varchar(4000) not null,
        primary key (id)
    );

    create table if not exists password_recovery (
        completed_at timestamp(6) with time zone,
        expires_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        requested_at timestamp(6) with time zone,
        revision bigint not null,
        user_id bigint not null,
        token_hash varchar(64) unique,
        issued_by varchar(255),
        nickname varchar(255),
        verification clob,
        primary key (id)
    );

    create table if not exists project (
        target_date date,
        created_at timestamp(6) not null,
        created_by bigint not null,
        department_id bigint not null,
        id bigint generated by default as identity,
        revision bigint not null,
        name varchar(150) not null,
        description varchar(4000) not null,
        status enum ('ACTIVE','CLOSED','PLANNING','RELEASED','REVIEW') not null,
        primary key (id)
    );

    create table if not exists project_member (
        id bigint generated by default as identity,
        project_id bigint not null,
        user_id bigint not null,
        role enum ('CONTRIBUTOR','ENGINEERING','OWNER','QUALITY','SECURITY','VIEWER') not null,
        primary key (id),
        constraint uk_project_member unique (project_id, user_id)
    );

    create table if not exists project_release (
        release_number integer not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        quality_run_id bigint,
        recalled_at timestamp(6) with time zone,
        released_at timestamp(6) with time zone,
        revision bigint not null,
        security_assessment_id bigint,
        fingerprint varchar(64) not null,
        recalled_by varchar(255),
        released_by varchar(255),
        notes clob,
        recall_reason clob,
        primary key (id),
        constraint uk_project_release_number unique (project_id, release_number)
    );

    create table if not exists project_requirement (
        minimum_count integer not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        category enum ('DESIGN','OTHER','SECURITY_REVIEW','TEST_REPORT') not null,
        primary key (id),
        constraint uk_project_requirement unique (project_id, category)
    );

    create table if not exists quality_check (
        active boolean not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        revision bigint not null,
        criterion varchar(300) not null,
        primary key (id)
    );

    create table if not exists quality_result (
        passed boolean not null,
        check_id bigint not null,
        id bigint generated by default as identity,
        run_id bigint not null,
        criterion varchar(300) not null,
        primary key (id),
        constraint uk_quality_result unique (run_id, check_id)
    );

    create table if not exists quality_run (
        passed boolean not null,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        project_id bigint not null,
        retest_of bigint,
        tester_id bigint,
        fingerprint varchar(64) not null,
        tester_name varchar(255),
        evidence clob not null,
        primary key (id)
    );

    create table if not exists release_item (
        id bigint generated by default as identity,
        release_id bigint not null,
        version_id bigint not null,
        primary key (id),
        constraint uk_release_version unique (release_id, version_id)
    );

    create table if not exists release_recipient (
        id bigint generated by default as identity,
        release_id bigint not null,
        user_id bigint not null,
        nickname varchar(255),
        primary key (id),
        constraint uk_release_recipient unique (release_id, user_id)
    );

    create table if not exists review_note (
        author_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        version_id bigint not null,
        decision varchar(30) not null,
        author_name varchar(100) not null,
        content clob not null,
        primary key (id)
    );

    create table if not exists security_assessment (
        approved boolean not null,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        project_id bigint not null,
        reviewer_id bigint,
        fingerprint varchar(64) not null,
        reviewer_name varchar(255),
        findings clob not null,
        primary key (id)
    );

    create table if not exists temporary_access (
        approved_at timestamp(6) with time zone,
        approved_by bigint,
        document_id bigint not null,
        expires_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        requested_at timestamp(6) with time zone not null,
        requested_until timestamp(6) with time zone not null,
        revision bigint not null,
        user_id bigint not null,
        requester_name varchar(100) not null,
        decision_reason clob,
        reason clob not null,
        status enum ('APPROVED','REJECTED','REQUESTED','REVOKED') not null,
        primary key (id)
    );

    create table if not exists users (
        created_at timestamp(6) not null,
        credentials_version bigint default 0 not null,
        department bigint,
        id bigint generated by default as identity,
        revision bigint default 0 not null,
        nickname varchar(100) not null unique,
        email varchar(255) not null unique,
        password varchar(255) not null,
        account_status enum ('ACTIVE','BAN','DELETED','LOCKED') not null,
        clearance enum ('CONFIDENTIAL','INTERNAL','RESTRICTED') default 'INTERNAL' not null,
        position enum ('ADMIN','ASSISTANT_MANAGER','DEPUTY_GENERAL_MANAGER','EXECUTIVE','GENERAL_MANAGER','MANAGER','STAFF') not null,
        primary key (id)
    );

    create index if not exists ix_attachment_version
       on attachment (version_id);

    create index if not exists idx_audit_project
       on audit_record (project_id, id);

    create index if not exists idx_audit_actor
       on audit_record (actor, id);

    create index if not exists idx_audit_action
       on audit_record (action, id);

    create index if not exists IDX_department_notice_recent
       on department_notice (department_id, created_at, id);

    create index if not exists IDX_activity_time
       on document_activity (occurred_at, id);

    create index if not exists IDX_activity_actor
       on document_activity (actor_id, occurred_at);

    create index if not exists IDX_activity_document
       on document_activity (document_id, occurred_at);

    create index if not exists IDX_document_version_review
       on document_version (status, created_at);

    create index if not exists ix_change_project
       on engineering_change (project_id, status);

    create index if not exists ix_nonconformity_project
       on nonconformity (project_id, closed);

    create index if not exists idx_notification_recipient
       on notification (recipient_id, read_at, id);

    create index if not exists ix_recovery_user
       on password_recovery (user_id, completed_at);

    create index if not exists idx_project_department
       on project (department_id, status);

    create index if not exists idx_membership_user
       on project_member (user_id, project_id);

    create index if not exists ix_quality_check_project
       on quality_check (project_id, active);

    create index if not exists ix_quality_run_project
       on quality_run (project_id, id);

    create index if not exists idx_review_note_version
       on review_note (version_id, id);

    create index if not exists ix_security_assessment_project
       on security_assessment (project_id, id);

    create index if not exists idx_temporary_access_effective
       on temporary_access (document_id, user_id, status, expires_at);

    alter table if exists department_notice
       add constraint if not exists FK4jvoasjcve9xu0t67wvshdseo
       foreign key (author_id)
       references users;

    alter table if exists department_notice
       add constraint if not exists FKrsyxri2to469s59lr5oxw6sn3
       foreign key (department_id)
       references department;

    alter table if exists document
       add constraint if not exists FKqm5yun3pd54ydxd495j3sj01k
       foreign key (author_id)
       references users;

    alter table if exists document
       add constraint if not exists FKh59xigx0r4b66bcg7p3etmcyg
       foreign key (department_id)
       references department;

    alter table if exists document
       add constraint if not exists FKebvohyx0uckt4eb2cpiqiciba
       foreign key (project_id)
       references project;

    alter table if exists document_version
       add constraint if not exists FKnvpdtplqabenasvgs0q5e3db4
       foreign key (document_id)
       references document;

    alter table if exists document_version
       add constraint if not exists FKhyj39gccg60nelqpyshdrbrs6
       foreign key (reviewed_by_id)
       references users;

    alter table if exists project
       add constraint if not exists FK130q86aiyxo2fdp6lytxvwoxx
       foreign key (created_by)
       references users;

    alter table if exists project
       add constraint if not exists FKl7ga8i4ry2amd4mb525tdmjf6
       foreign key (department_id)
       references department;

    alter table if exists project_member
       add constraint if not exists FK103dwxad12nbaxtmnwus4eft2
       foreign key (project_id)
       references project;

    alter table if exists project_member
       add constraint if not exists FKmep5284pv47j2o523l14wyx4g
       foreign key (user_id)
       references users;

    alter table if exists project_requirement
       add constraint if not exists FK1wpcsw37qwayff3tg45l87996
       foreign key (project_id)
       references project;

    alter table if exists review_note
       add constraint if not exists FKfwgcxj0c1somsdckcdq29pvae
       foreign key (version_id)
       references document_version;

    alter table if exists users
       add constraint if not exists FK_department
       foreign key (department)
       references department;
