-- Preserve the actual document versions examined in each new review.
-- Historical fingerprints cannot reliably reconstruct version lists, so no backfill is attempted.
CREATE TABLE review_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quality_run_id BIGINT,
    security_assessment_id BIGINT,
    version_id BIGINT NOT NULL,
    CONSTRAINT ck_review_document_owner CHECK (
        (quality_run_id IS NOT NULL AND security_assessment_id IS NULL)
        OR (quality_run_id IS NULL AND security_assessment_id IS NOT NULL)
    ),
    CONSTRAINT fk_review_document_quality FOREIGN KEY (quality_run_id) REFERENCES quality_run(id),
    CONSTRAINT fk_review_document_security FOREIGN KEY (security_assessment_id) REFERENCES security_assessment(id),
    CONSTRAINT fk_review_document_version FOREIGN KEY (version_id) REFERENCES document_version(id),
    CONSTRAINT uk_review_document_quality UNIQUE (quality_run_id, version_id),
    CONSTRAINT uk_review_document_security UNIQUE (security_assessment_id, version_id)
);
